- name: install base soft
  yum: name={{ item }}  state=present
  with_items:
    - vim
    - gcc
    - net-tools
    - wget 
    - man
    - libselinux-python
- name: install CentOS6  epel 
  get_url: dest=/etc/yum.repos.d/epel.repo url=http://mirrors.aliyun.com/repo/epel-6.repo
  when: ansible_distribution_major_version == "6"
- name: install CentOS7  epel 
  get_url: dest=/etc/yum.repos.d/epel.repo url=http://mirrors.aliyun.com/repo/epel-7.repo
  when: ansible_distribution_major_version == "7"
